spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50} -%msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50} -%msg%n"
  level:
    root: info
    yonmin: debug
  file:
    name: log/blog.log
    max-size: 1MB
    max-history: 7